---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This repository contains simulation results related to SuSiE-RSS.

+ Most recent results: 
  
    - [Paper](paper_figures.html)

+ Previous results:
    
    SuSiE-RSS uses $\hat{z} \sim N(R z, R)$.
    
    - [RESULT](susierss_ukb_20210324.html)
    
    - [inconsistency between z and LD, elbo
	   problem](susierss_notconsistent_elbo.html)
    
    - [20210324 result ref1000](susierss_ukb_20210324_ref1000.html)

    - [20210324 result ref500](susierss_ukb_20210324_ref500.html)
    
    - [20210324 result ref500 LD eg](susierss_ukb_20210324_ref500_ldref.html)

    - [power vs. FDR plots for paper](power_vs_fdr.html)

    - [PIP calibration and power vs. FDR](susierss_ukb_20210218.html)
 
    - [example](susierss_ukb_20210218_example.html)
    
    - [susie convergence benchmark](susie_ukb_20210307_convergence.html)
    
    - [susie convergence problem](susie_convergence_problem.html)
    
    - [susie convergence possible
	   solution](susie_convergence_possible_sol.html)
    
    - [susierss with 3 steps procedure](susierss_3steps_ukb_20210314.html)
